# WARNING: This compose.yml is configured for postgres database only.
#          Adjust to your database needs.

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
     - "${REDIS_PORT}:6379"
    volumes:
      - cache:/data

volumes:
  data:
    driver: local
  cache:
    driver: local
