name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: actions/checkout@v4
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose

      - name: Clippy
        run: cargo clippy -- --deny warnings

      - name: Fmt
        run: cargo fmt -- --check

      - name: Test
        run: DATABASE_VARIANT=mock cargo test --verbose
